service: recipe-parser
provider:
  name: aws
  runtime: nodejs12.x
plugins:
  - serverless-webpack
custom:
  webpack:
    includeModules: true
functions:
  parse:
    handler: handler.parse
    events:
      - http:
          path: parse
          method: post
